/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import classes.Informações;
import javax.swing.JOptionPane;

/**
 *
 * @author relan
 */
public class Aplicacao extends javax.swing.JFrame {
  private Tela Tela;
  private Informações informacao = new Informações();
    /**
     * Creates new form Aplicacao
     */
    public Aplicacao() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCalculadora = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemFormula = new javax.swing.JMenuItem();
        jMenuItemAutores = new javax.swing.JMenuItem();
        jMenuItemObjetivo = new javax.swing.JMenuItem();
        jMenuItemVersao = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APP - CalcRes");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/Calc-res.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jMenu1.setText("Operações");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItemCalculadora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemCalculadora.setText("Calculadora");
        jMenuItemCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCalculadoraActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCalculadora);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Informações");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItemFormula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemFormula.setText("Fórmulas");
        jMenuItemFormula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFormulaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemFormula);

        jMenuItemAutores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemAutores.setText("Autores");
        jMenuItemAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAutoresActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemAutores);

        jMenuItemObjetivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemObjetivo.setText("Objetivo");
        jMenuItemObjetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemObjetivoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemObjetivo);

        jMenuItemVersao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemVersao.setText("Versão do Programa");
        jMenuItemVersao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVersaoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemVersao);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Opções");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItemSair.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemSair);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCalculadoraActionPerformed
        // TODO add your handling code here:
        Tela = new Tela(this,true);
        Tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemCalculadoraActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAutoresActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,informacao.autores(),"Autores",1);
    }//GEN-LAST:event_jMenuItemAutoresActionPerformed

    private void jMenuItemObjetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemObjetivoActionPerformed
        // TODO add your handling code here:
          JOptionPane.showMessageDialog(this,informacao.objetivo(),"Objetivo",1);
    }//GEN-LAST:event_jMenuItemObjetivoActionPerformed

    private void jMenuItemVersaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVersaoActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this,informacao.versao(),"Versão",1);
    }//GEN-LAST:event_jMenuItemVersaoActionPerformed

    private void jMenuItemFormulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFormulaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,informacao.formulas(),"Fórmulas",1);
    }//GEN-LAST:event_jMenuItemFormulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAutores;
    private javax.swing.JMenuItem jMenuItemCalculadora;
    private javax.swing.JMenuItem jMenuItemFormula;
    private javax.swing.JMenuItem jMenuItemObjetivo;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemVersao;
    // End of variables declaration//GEN-END:variables
}
