/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import classes.Calculadora;
import javax.swing.JOptionPane;

/**
 *
 * @author relan
 */
public class Tela extends javax.swing.JDialog {
    private Calculadora calculadora;
    /**
     * Creates new form Tela
     */
    public Tela(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCalc = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jButtonCalcular = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaResultado = new javax.swing.JTextArea();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldFonte = new javax.swing.JTextField();
        jTextFieldLed = new javax.swing.JTextField();
        jTextFieldCorrenteLed = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelQnt = new javax.swing.JLabel();
        jTextFieldQuantidade = new javax.swing.JTextField();

        jLabel6.setText("(V)");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculadora - LED");

        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        buttonGroupCalc.add(jRadioButton1);
        jRadioButton1.setText("Um LED");
        jRadioButton1.setActionCommand("A");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verificaClick(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jTextAreaResultado.setColumns(20);
        jTextAreaResultado.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jTextAreaResultado.setRows(5);
        jScrollPane1.setViewportView(jTextAreaResultado);

        buttonGroupCalc.add(jRadioButton2);
        jRadioButton2.setText("LED em série");
        jRadioButton2.setActionCommand("B");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verificaClick(evt);
            }
        });

        buttonGroupCalc.add(jRadioButton3);
        jRadioButton3.setText("LED em paralelo");
        jRadioButton3.setActionCommand("C");
        jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verificaClick(evt);
            }
        });

        jLabel1.setText("Tensão da Fonte:");

        jLabel2.setText("Tensão do Led:");

        jLabel3.setText("Corrente do Led:");

        jLabel4.setText("(V)");

        jLabel5.setText("(V)");

        jLabel7.setText("(mA)");

        jLabelQnt.setText("Quantidade de Leds: ");

        jTextFieldQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuantidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton2)
                        .addGap(119, 119, 119)
                        .addComponent(jRadioButton3)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabelQnt))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldFonte)
                            .addComponent(jTextFieldLed)
                            .addComponent(jTextFieldCorrenteLed, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(jTextFieldQuantidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(jButtonLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(36, 36, 36))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldFonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldLed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldCorrenteLed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButtonCalcular)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLimpar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQnt)
                    .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed
    private void desligarCampo(){
        if(buttonGroupCalc.getSelection().getActionCommand().equals("A")){
            jLabelQnt.setEnabled(false);
            jTextFieldQuantidade.setEnabled(false);
        }
        if(!buttonGroupCalc.getSelection().getActionCommand().equals("A")){
             jLabelQnt.setEnabled(true);
             jTextFieldQuantidade.setEnabled(true);
        }
    }
    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        // TODO add your handling code here
          calculadora = new Calculadora();
          
          if(jTextFieldFonte.getText().isEmpty()){
              JOptionPane.showMessageDialog(this, "Preencha o campo da tensão da fonte", "Aviso",0);
            jTextFieldFonte.requestFocusInWindow();
            return;
        }
           if(jTextFieldCorrenteLed.getText().isEmpty()){
              JOptionPane.showMessageDialog(this, "Preencha o campo da corrente", "Aviso",0);
            jTextFieldCorrenteLed.requestFocusInWindow();
            return;
        }
           if(jTextFieldLed.getText().isEmpty()){
              JOptionPane.showMessageDialog(this, "Preencha o campo da tensão do led", "Aviso",0);
            jTextFieldLed.requestFocusInWindow();
            return;
        }
           
      if(buttonGroupCalc.getSelection().getActionCommand().equals("A")){
          calculadora.setCorrente(Double.parseDouble(jTextFieldCorrenteLed.getText()));
          calculadora.setTensaoFonte(Double.parseDouble(jTextFieldFonte.getText()));
          calculadora.setTensaoLed(Double.parseDouble(jTextFieldLed.getText()));
          jTextAreaResultado.setText("Valor do resistor : " + calculadora.resistor()+ "(Ω)" 
          + "\nPara Ligar esse Led é necessário um resistor de " + calculadora.resistor() + "(Ω)" 
          );
      }
      
       if(buttonGroupCalc.getSelection().getActionCommand().equals("B")){
          calculadora.setCorrente(Double.parseDouble(jTextFieldCorrenteLed.getText()));
          calculadora.setTensaoFonte(Double.parseDouble(jTextFieldFonte.getText()));
          calculadora.setQuantidade(Integer.parseInt(jTextFieldQuantidade.getText()));
          calculadora.setTensaoLed(Double.parseDouble(jTextFieldLed.getText()));

          
          jTextAreaResultado.setText("Valor do resistor : " + calculadora.resistorSerie()+ "(Ω)" 
          + "\nPara Ligar esses Led's em série será \nnecessário um resistor de " + calculadora.resistorSerie() + "(Ω)" 
          );
      }
     
        if(buttonGroupCalc.getSelection().getActionCommand().equals("C")){
          calculadora.setCorrente(Double.parseDouble(jTextFieldCorrenteLed.getText()));
          calculadora.setTensaoFonte(Double.parseDouble(jTextFieldFonte.getText()));
          calculadora.setQuantidade(Integer.parseInt(jTextFieldQuantidade.getText()));
          calculadora.setTensaoLed(Double.parseDouble(jTextFieldLed.getText()));

          
          jTextAreaResultado.setText("Valor do resistor : " + calculadora.resistorParalelo()+ "(Ω)" 
          + "\nPara Ligar esses Led's em série será \nnecessário um resistor de " + calculadora.resistorParalelo() + "(Ω)" 
          );
      }
           
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:
            jTextFieldCorrenteLed.setText(null);
            jTextFieldFonte.setText(null);
            jTextFieldLed.setText(null);
            jTextAreaResultado.setText(null);
            jTextFieldFonte.requestFocusInWindow();
            buttonGroupCalc.clearSelection();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jTextFieldQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuantidadeActionPerformed

    private void verificaClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verificaClick
        // TODO add your handling code here:
        desligarCampo();
    }//GEN-LAST:event_verificaClick

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCalc;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelQnt;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaResultado;
    private javax.swing.JTextField jTextFieldCorrenteLed;
    private javax.swing.JTextField jTextFieldFonte;
    private javax.swing.JTextField jTextFieldLed;
    private javax.swing.JTextField jTextFieldQuantidade;
    // End of variables declaration//GEN-END:variables
}
